wandb_version: 1

model_type:
  desc: null
  value: phi2-3b
train_dataset_sample:
  desc: null
  value: 41600
eval_steps:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 32
num_train_epochs:
  desc: null
  value: 1
max_length:
  desc: null
  value: 512
learning_rate:
  desc: null
  value: 2.0e-05
dataset:
  desc: null
  value:
  - alpaca-en
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.39.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713345061.0
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      - 105
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      - 105
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.16.5
      6: 4.39.2
      8:
      - 5
      13: linux-x86_64
