wandb_version: 1

model_type:
  desc: null
  value: phi2-3b
model_id_or_path:
  desc: null
  value: AI-ModelScope/phi-2
model_revision:
  desc: null
  value: master
model_layer_cls_name:
  desc: null
  value: null
sft_type:
  desc: null
  value: full
freeze_parameters:
  desc: null
  value: 0.0
additional_trainable_parameters:
  desc: null
  value: []
tuner_backend:
  desc: null
  value: peft
template_type:
  desc: null
  value: default
output_dir:
  desc: null
  value: /home/nlp_class/swift/examples/pytorch/llm/scripts/phi2_3b/lora/output/phi2-3b/v9-20240417-160525
add_output_dir_suffix:
  desc: null
  value: true
ddp_backend:
  desc: null
  value: null
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_broadcast_buffers:
  desc: null
  value: null
seed:
  desc: null
  value: 42
resume_from_checkpoint:
  desc: null
  value: null
dtype:
  desc: null
  value: bf16
dataset:
  desc: null
  value:
  - alpaca-en
dataset_seed:
  desc: null
  value: 42
dataset_test_ratio:
  desc: null
  value: 0.01
train_dataset_sample:
  desc: null
  value: 41600
train_dataset_mix_ratio:
  desc: null
  value: 0.0
train_dataset_mix_ds:
  desc: null
  value:
  - ms-bench
val_dataset_sample:
  desc: null
  value: null
use_loss_scale:
  desc: null
  value: false
system:
  desc: null
  value: null
max_length:
  desc: null
  value: 512
truncation_strategy:
  desc: null
  value: delete
check_dataset_strategy:
  desc: null
  value: none
custom_train_dataset_path:
  desc: null
  value: []
custom_val_dataset_path:
  desc: null
  value: []
self_cognition_sample:
  desc: null
  value: 0
model_name:
  desc: null
  value:
  - null
  - null
model_author:
  desc: null
  value:
  - null
  - null
quantization_bit:
  desc: null
  value: 0
bnb_4bit_comp_dtype:
  desc: null
  value: bf16
bnb_4bit_quant_type:
  desc: null
  value: nf4
bnb_4bit_use_double_quant:
  desc: null
  value: true
bnb_4bit_quant_storage:
  desc: null
  value: null
lora_target_modules:
  desc: null
  value:
  - Wqkv
lora_rank:
  desc: null
  value: 8
lora_alpha:
  desc: null
  value: 32
lora_dropout_p:
  desc: null
  value: 0.05
lora_bias_trainable:
  desc: null
  value: none
lora_modules_to_save:
  desc: null
  value: []
lora_dtype:
  desc: null
  value: fp32
lora_lr_ratio:
  desc: null
  value: null
use_rslora:
  desc: null
  value: false
use_dora:
  desc: null
  value: false
adapter_act:
  desc: null
  value: gelu
adapter_length:
  desc: null
  value: 128
use_galore:
  desc: null
  value: false
galore_rank:
  desc: null
  value: 128
galore_target_modules:
  desc: null
  value: null
galore_update_proj_gap:
  desc: null
  value: 50
galore_scale:
  desc: null
  value: 1.0
galore_proj_type:
  desc: null
  value: std
galore_optim_per_parameter:
  desc: null
  value: false
galore_with_embedding:
  desc: null
  value: false
adalora_target_r:
  desc: null
  value: 8
adalora_init_r:
  desc: null
  value: 12
adalora_tinit:
  desc: null
  value: 0
adalora_tfinal:
  desc: null
  value: 0
adalora_deltaT:
  desc: null
  value: 1
adalora_beta1:
  desc: null
  value: 0.85
adalora_beta2:
  desc: null
  value: 0.85
adalora_orth_reg_weight:
  desc: null
  value: 0.5
ia3_target_modules:
  desc: null
  value:
  - DEFAULT
ia3_feedforward_modules:
  desc: null
  value: []
ia3_modules_to_save:
  desc: null
  value: []
llamapro_num_new_blocks:
  desc: null
  value: 4
llamapro_num_groups:
  desc: null
  value: null
neftune_noise_alpha:
  desc: null
  value: null
neftune_backend:
  desc: null
  value: transformers
gradient_checkpointing:
  desc: null
  value: false
deepspeed:
  desc: null
  value: null
batch_size:
  desc: null
  value: 32
eval_batch_size:
  desc: null
  value: 32
num_train_epochs:
  desc: null
  value: 1
max_steps:
  desc: null
  value: -1
optim:
  desc: null
  value: AGMA
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
learning_rate:
  desc: null
  value: 2.0e-05
weight_decay:
  desc: null
  value: 0.1
gradient_accumulation_steps:
  desc: null
  value: 1
max_grad_norm:
  desc: null
  value: 0.5
predict_with_generate:
  desc: null
  value: false
lr_scheduler_type:
  desc: null
  value: linear
warmup_ratio:
  desc: null
  value: 0.05
eval_steps:
  desc: null
  value: 10
save_steps:
  desc: null
  value: 10
save_only_model:
  desc: null
  value: true
save_total_limit:
  desc: null
  value: 2
logging_steps:
  desc: null
  value: 5
dataloader_num_workers:
  desc: null
  value: 1
dataloader_pin_memory:
  desc: null
  value: true
push_to_hub:
  desc: null
  value: false
hub_model_id:
  desc: null
  value: null
hub_token:
  desc: null
  value: null
hub_private_repo:
  desc: null
  value: false
push_hub_strategy:
  desc: null
  value: push_best
test_oom_error:
  desc: null
  value: false
disable_tqdm:
  desc: null
  value: false
lazy_tokenize:
  desc: null
  value: false
preprocess_num_proc:
  desc: null
  value: 1
use_flash_attn:
  desc: null
  value: true
ignore_args_error:
  desc: null
  value: false
check_model_is_latest:
  desc: null
  value: true
logging_dir:
  desc: null
  value: /home/nlp_class/swift/examples/pytorch/llm/scripts/phi2_3b/lora/output/phi2-3b/v9-20240417-160525/runs
report_to:
  desc: null
  value:
  - tensorboard
acc_strategy:
  desc: null
  value: token
save_on_each_node:
  desc: null
  value: true
evaluation_strategy:
  desc: null
  value: steps
save_strategy:
  desc: null
  value: steps
save_safetensors:
  desc: null
  value: true
gpu_memory_fraction:
  desc: null
  value: null
max_new_tokens:
  desc: null
  value: 2048
do_sample:
  desc: null
  value: true
temperature:
  desc: null
  value: 0.3
top_k:
  desc: null
  value: 20
top_p:
  desc: null
  value: 0.7
repetition_penalty:
  desc: null
  value: 1.0
num_beams:
  desc: null
  value: 1
per_device_train_batch_size:
  desc: null
  value: null
per_device_eval_batch_size:
  desc: null
  value: null
only_save_model:
  desc: null
  value: null
neftune_alpha:
  desc: null
  value: null
deepspeed_config_path:
  desc: null
  value: null
model_cache_dir:
  desc: null
  value: null
fsdp:
  desc: null
  value: ''
fsdp_config:
  desc: null
  value: null
lora_use_embedding:
  desc: null
  value: false
lora_use_all:
  desc: null
  value: false
lora_m2s_use_embedding:
  desc: null
  value: false
lora_m2s_use_ln:
  desc: null
  value: false
torch_dtype:
  desc: null
  value: torch.bfloat16
fp16:
  desc: null
  value: false
bf16:
  desc: null
  value: true
bnb_4bit_compute_dtype:
  desc: null
  value: torch.bfloat16
load_in_4bit:
  desc: null
  value: false
load_in_8bit:
  desc: null
  value: false
train_sampler_random:
  desc: null
  value: true
training_args:
  desc: null
  value:
    output_dir: /home/nlp_class/swift/examples/pytorch/llm/scripts/phi2_3b/lora/output/phi2-3b/v9-20240417-160525
    overwrite_output_dir: false
    do_train: false
    do_eval: true
    do_predict: false
    evaluation_strategy: steps
    prediction_loss_only: false
    per_device_train_batch_size: 32
    per_device_eval_batch_size: 32
    per_gpu_train_batch_size: null
    per_gpu_eval_batch_size: null
    gradient_accumulation_steps: 1
    eval_accumulation_steps: null
    eval_delay: 0
    learning_rate: 2.0e-05
    weight_decay: 0.1
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_epsilon: 1.0e-08
    max_grad_norm: 0.5
    num_train_epochs: 1
    max_steps: -1
    lr_scheduler_type: linear
    lr_scheduler_kwargs: {}
    warmup_ratio: 0.05
    warmup_steps: 0
    log_level: passive
    log_level_replica: warning
    log_on_each_node: true
    logging_dir: /home/nlp_class/swift/examples/pytorch/llm/scripts/phi2_3b/lora/output/phi2-3b/v9-20240417-160525/runs
    logging_strategy: steps
    logging_first_step: true
    logging_steps: 5
    logging_nan_inf_filter: true
    save_strategy: steps
    save_steps: 10
    save_total_limit: 2
    save_safetensors: true
    save_on_each_node: true
    save_only_model: true
    no_cuda: false
    use_cpu: false
    use_mps_device: false
    seed: 42
    data_seed: null
    jit_mode_eval: false
    use_ipex: false
    bf16: true
    fp16: false
    fp16_opt_level: O1
    half_precision_backend: auto
    bf16_full_eval: false
    fp16_full_eval: false
    tf32: null
    local_rank: 0
    ddp_backend: null
    tpu_num_cores: null
    tpu_metrics_debug: false
    debug: []
    dataloader_drop_last: false
    eval_steps: 10
    dataloader_num_workers: 1
    dataloader_prefetch_factor: null
    past_index: -1
    run_name: /home/nlp_class/swift/examples/pytorch/llm/scripts/phi2_3b/lora/output/phi2-3b/v9-20240417-160525
    disable_tqdm: false
    remove_unused_columns: false
    label_names: null
    load_best_model_at_end: false
    metric_for_best_model: loss
    greater_is_better: false
    ignore_data_skip: false
    fsdp: []
    fsdp_min_num_params: 0
    fsdp_config:
      min_num_params: 0
      xla: false
      xla_fsdp_v2: false
      xla_fsdp_grad_ckpt: false
    fsdp_transformer_layer_cls_to_wrap: null
    accelerator_config:
      split_batches: false
      dispatch_batches: null
      even_batches: true
      use_seedable_sampler: true
    deepspeed: null
    label_smoothing_factor: 0.0
    optim: AGMA
    optim_args: null
    adafactor: false
    group_by_length: false
    length_column_name: length
    report_to:
    - tensorboard
    ddp_find_unused_parameters: null
    ddp_bucket_cap_mb: null
    ddp_broadcast_buffers: null
    dataloader_pin_memory: true
    dataloader_persistent_workers: false
    skip_memory_metrics: true
    use_legacy_prediction_loop: false
    push_to_hub: false
    resume_from_checkpoint: null
    hub_model_id: null
    hub_strategy: every_save
    hub_token: null
    hub_private_repo: false
    hub_always_push: false
    gradient_checkpointing: false
    gradient_checkpointing_kwargs: null
    include_inputs_for_metrics: false
    fp16_backend: auto
    push_to_hub_model_id: null
    push_to_hub_organization: null
    push_to_hub_token: null
    _n_gpu: 8
    mp_parameters: ''
    auto_find_batch_size: false
    full_determinism: false
    torchdynamo: null
    ray_scope: last
    ddp_timeout: 1800
    torch_compile: false
    torch_compile_backend: null
    torch_compile_mode: null
    dispatch_batches: null
    split_batches: null
    include_tokens_per_second: false
    include_num_input_tokens_seen: false
    neftune_noise_alpha: null
    optim_target_modules: null
    sortish_sampler: true
    predict_with_generate: false
    generation_max_length: null
    generation_num_beams: null
    generation_config: null
    train_sampler_random: true
    push_hub_strategy: push_best
    acc_strategy: token
    additional_saved_files: []
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.39.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713341126.0
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      - 105
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      - 105
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.16.5
      6: 4.39.2
      8:
      - 5
      13: linux-x86_64
